### ISSUE TITLE
Mention that this is only gruvbox dark mode, or document the light mode

### ISSUE THREAD

**Issue by roryokane** [flyingfisch/VSGruvbox#2]
The README only shows screenshots for the “dark mode” version of gruvbox. You should change the description to say that the UI theme implements “gruvbox dark mode” or “gruvbox dark”, not “gruvbox”. Or if you have actually implemented light mode too, you should include a screenshot of it.

**Comment by flyingfisch** [comment]
Good point, I'll update it.
